### ISSUE TITLE
File Name

### ISSUE THREAD

**Issue by someamon** [HttpMarco/Aeon#8]
wenn ich via. Option den file name setze wird nur ein .ae file erstellt und nicht der angegebene

![grafik](https://user-images.githubusercontent.com/103960818/209431865-77487276-7ed1-4e58-b2df-efd8b5ac8ace.png)
![grafik](https://user-images.githubusercontent.com/103960818/209431868-e1983771-8241-407e-abf5-8289979e1980.png)

**Comment by HttpMarco** [comment]
Hey, grundsätzlich war die Idee, dass man keine endnung angeben muss. Also nur 'node'. Ich schaue aber mal ob ich beides supporte.

**Comment by someamon** [comment]
Ich hatte es auch ohne .aeon versucht. Es ist trotzdem der gezeigte File raus gekommen
